### ISSUE TITLE
Indentation issue on Readme.md files

### ISSUE THREAD

**Issue by Silber8806** [jessupjs/s14a2020#1]
Some of code on Lab 3 has python classes and functions where the indent is not appearing properly.  So instead of:

```
def foo():
    print("IRA Function")
```

it's looking like:

```
def foo():
print("IRA Function")
```

which will throw a syntax error for sure.  Seeing it in both classes and functions.  Example below:

```
class UserForm(FlaskForm):
first_name = StringField('First Name', validators=[DataRequired()])
age = IntegerField('Age', validators=[DataRequired()])
submit = SubmitField('Enter')
```

**Comment by Silber8806** [comment]
Ops.. mean lab 3.  I have example below:

`class UserForm(FlaskForm):
first_name = StringField('First Name', validators=[DataRequired()])
age = IntegerField('Age', validators=[DataRequired()])
submit = SubmitField('Enter')`

**Comment by jessupjs** [comment]
Good catch! Made some updates to Lab3/readme.md.  Thanks for sharing, and always feel free to make a pull request.

**Comment by jessupjs** [comment]
No new probs reported.
